# Generated by Django 3.2.7 on 2021-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
